name: Build Android Kernels

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        android_version:
          [
            "android12-5.10-lts",
            "android13-5.10-lts",
            "android13-5.15-lts",
            "android14-5.15-lts",
            "android14-6.1-lts"
          ]
    steps:
      - name: Common setup
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Clone Repo
        run: |
          git clone https://github.com/aosp-mirror/kernel_common.git -b ${{ matrix.android_version }}

      - name: Build Android Kernel
        run: |

          cd kernel_common
          make ARCH=arm64 defconfig
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=aarch64-linux-gnu-gcc

      - name: Upload Kernel
        uses: actions/upload-artifact@v4.0.0
        with:
          name: kernel-${{ matrix.android_version }}
          path: kernel_common/arch/arm64/boot/
