name: Wsl2-Kernel-Build
on: [push,workflow_dispatch]

jobs:
  my-jobs:
    runs-on: ubuntu-20.04

    steps:
      - name: wget kernel
        run: |
          wget https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-5.10.102.1.tar.gz
          tar xvzf ./linux-msft-wsl-5.10.102.1.tar.gz
     # - name: SSH
       # uses: P3TERX/ssh2actions@main
       # env:
         # TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         # TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - name: config 
        run: |
          wget https://github.com/lurenjia534/WSL2_Kernel_Build_Action/blob/main/Kernel.config
          mv kernel.config .config
          mv .config WSL2-Linux-Kernel-linux-msft-wsl-5.10.102.1/
          cd WSL2-Linux-Kernel-linux-msft-wsl-5.10.102.1/
          
      - name: apt-get
        run: |
          sudo apt update
          sudo apt install build-essential flex bison libssl-dev libelf-dev dwarves
      - name: build
        run: |
          cd WSL2-Linux-Kernel-linux-msft-wsl-5.10.102.1/
          make j8
