name: Wsl2 Kernel Build
on: [workflow_dispatch]

jobs:
  my-jobs:
    runs-on: ubuntu-22.04

    steps:

      - name: Clone latest kernel source code
        run: |
          git clone https://github.com/microsoft/WSL2-Linux-Kernel.git
          cd WSL2-Linux-Kernel
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: config 
        run: |
          cd WSL2-Linux-Kernel
          wget https://raw.githubusercontent.com/lurenjia534/WSL2_Kernel_Build_Action/main/.config
          
      - name: apt-get
        run: |
          sudo apt update
          sudo apt install build-essential flex bison libssl-dev libelf-dev dwarves
          
      - name: build
        run: |
          cd WSL2-Linux-Kernel
          make -j$(nproc) KCONFIG_CONFIG=.config

      - name: upload
        uses: actions/upload-artifact@v4.0.0
        with: 
          name: kernel
          path: WSL2-Linux-Kernel/arch/x86/boot/bzImage
